/*
 * Copyright (C) 2016 Baidu, Inc. All Rights Reserved.
 */
package com.baidu.rigel.jichuang.bo;

import java.io.Serializable;
import java.util.Collections;
import java.util.Date;
import java.util.Map;
import java.util.WeakHashMap;

/**
 * This bo is map to table : tb_reach_result
 * Table description : 触达记录
 *
 * @author BJF
 */
public abstract class ReachResultBase implements Serializable {
    /**
     * serial Version UID.
     */
    private static final long serialVersionUID = -1L;

    /**
     * hashCode temporary storage.
     */
    private volatile Long hashCode;

    /**
     * Use a WeakHashMap so entries will be garbage collected once all entities
     * referring to a saved hash are garbage collected themselves.
     */
    private static final Map<Serializable, Long> SAVED_HASHES =
            Collections.synchronizedMap(new WeakHashMap<Serializable, Long>());

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reach_result.id
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */

    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reach_result.address
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reach_result.price
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    private Long price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reach_result.defective_rate
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    private Long defectiveRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reach_result.stock
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    private Long stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reach_result.productivity
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    private Long productivity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reach_result.register_capita
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    private Long registerCapita;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reach_result.relation_id
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    private Long relationId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reach_result.reach_category
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    private Long reachCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reach_result.reach_type
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    private Long reachType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reach_result.state
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    private Long state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reach_result.reach_date
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    private Date reachDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reach_result.response_date
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    private Date responseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reach_result.intention
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    private String intention;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reach_result.remark
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reach_result.id
     *
     * @return the value of tb_reach_result.id
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reach_result.address
     *
     * @return the value of tb_reach_result.address
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reach_result.price
     *
     * @return the value of tb_reach_result.price
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reach_result.defective_rate
     *
     * @return the value of tb_reach_result.defective_rate
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    public Long getDefectiveRate() {
        return defectiveRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reach_result.stock
     *
     * @return the value of tb_reach_result.stock
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    public Long getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reach_result.productivity
     *
     * @return the value of tb_reach_result.productivity
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    public Long getProductivity() {
        return productivity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reach_result.register_capita
     *
     * @return the value of tb_reach_result.register_capita
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    public Long getRegisterCapita() {
        return registerCapita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reach_result.relation_id
     *
     * @return the value of tb_reach_result.relation_id
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    public Long getRelationId() {
        return relationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reach_result.reach_category
     *
     * @return the value of tb_reach_result.reach_category
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    public Long getReachCategory() {
        return reachCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reach_result.reach_type
     *
     * @return the value of tb_reach_result.reach_type
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    public Long getReachType() {
        return reachType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reach_result.state
     *
     * @return the value of tb_reach_result.state
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reach_result.reach_date
     *
     * @return the value of tb_reach_result.reach_date
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    public Date getReachDate() {
        return reachDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reach_result.response_date
     *
     * @return the value of tb_reach_result.response_date
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    public Date getResponseDate() {
        return responseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reach_result.intention
     *
     * @return the value of tb_reach_result.intention
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    public String getIntention() {
        return intention;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reach_result.remark
     *
     * @return the value of tb_reach_result.remark
     *
     * @mbggenerated Sat Oct 29 05:21:56 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    @Override
    public int hashCode() {
        if (this.hashCode == null) {
            synchronized (this) {
                if (this.hashCode == null) {
                    Long newHashCode = null;
                    if (getId() != null) {
                        newHashCode = SAVED_HASHES.get(getId());
                    }

                    if (newHashCode == null) {
                        if (getId() != null) {
                            newHashCode = (long) getId().hashCode();
                        } else {
                            newHashCode = (long) super.hashCode();
                        }
                    }
                    this.hashCode = newHashCode;
                }
            }
        }
        return (int) (this.hashCode & 0xffffff);
    }

    @Override
    public boolean equals(final Object aThat) {

        if (this == aThat) {
            return true;
        }
        if (aThat == null) {
            return false;
        }
        if (!(aThat instanceof ReachResultBase)) {
            return false;
        }

        final ReachResultBase that = (ReachResultBase) aThat;
        boolean result = true;
        result = result && (((this.getId() == null) && (that.getId() == null)) || (this.getId() != null && this.getId()
                .equals(that.getId())));
        return result;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public void setPrice(Long price) {
        this.price = price;
    }

    public void setDefectiveRate(Long defectiveRate) {
        this.defectiveRate = defectiveRate;
    }

    public void setStock(Long stock) {
        this.stock = stock;
    }

    public void setProductivity(Long productivity) {
        this.productivity = productivity;
    }

    public void setRegisterCapita(Long registerCapita) {
        this.registerCapita = registerCapita;
    }

    public void setRelationId(Long relationId) {
        this.relationId = relationId;
    }

    public void setReachCategory(Long reachCategory) {
        this.reachCategory = reachCategory;
    }

    public void setReachType(Long reachType) {
        this.reachType = reachType;
    }

    public void setState(Long state) {
        this.state = state;
    }

    public void setReachDate(Date reachDate) {
        this.reachDate = reachDate;
    }

    public void setResponseDate(Date responseDate) {
        this.responseDate = responseDate;
    }

    public void setIntention(String intention) {
        this.intention = intention;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }
}